### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jingxizc** [LUHbots/luh_youbot_os#1]
Hi，I am working on the youbot for research,and I want to make the youbot catching the object on the conveyor( yeah, my research is interested in the catching the moving object) .I saw you group has made it ! I am excited ,and I want to konw how did you do that ? What algorithm did you use? Or can you give me some papers about that? Thank u  a lot! And my email is jingxizc@outlook.com!

**Comment by wentz89** [comment]
You might contact to info@luhbots.de
